arquivo2 = open('E:/Senai-SC - 2023/002 - Aulas/015 - Python/002 - Aulas Sergio - SLIDE/LerTXT/GOT.txt', 'w')
arquivo2.write('Escrevendo no arquivo\n')
arquivo2.write('John Snow\n')
arquivo2.write('Arya Stark\n')
arquivo2.write('Sansa Stark\n')
arquivo2.write('Bran Stark\n')
arquivo2.close()
print('Fim programa')
